#服务端口
server:
    port: 8025

################配置################
spring:
    application:
        #服务名称
        name: rocketmq-consumer-service

################swagger2配置################
#是否激活 swagger true or false
swagger:
    enable: true


################rocketmq配置################
rocketmq :
    consumer:
        # 是否开启自动配置
        isOnOff: on
        # 发送同一类消息设置为同一个group，保证唯一默认不需要设置，rocketmq会使用ip@pid（pid代表jvm名字）作为唯一标识
        groupName: "rocketmq_group_1001"
        # mq的nameserver地址
        namesrvAddr: 127.0.0.1:9876
        # 消费者订阅的主题topic和tags（*标识订阅该主题下所有的tags），格式: topic~tag1||tag2||tags3;
        topics: TestTopic~TestTag;TestTopic~HelloTag;HelloTopic~HelloTag;MyTopic~*
        # 消费者线程数据量
        consumeThreadMin: 5
        consumeThreadMax: 32
        # 设置一次消费信心的条数，默认1
        consumeMessageBatchMaxSize: 1