#服务端口
server:
    port: 8057

################配置################
spring:
    application:
        #服务名称
        name: rocketmq-consumer-service

################swagger2配置################
#是否激活 swagger true or false
swagger:
    enable: true


################rocketmq配置################
#而且注意这里不要写为spring.rocketmq.producer.group，这个版本的写法不一样（rocketmq-spring-boot-starte2.0.4）
rocketmq :
    # mq的nameserver地址
    name-server: 47.119.180.152:9876
    consumer:
        # 发送同一类消息设置为同一个group
        group1: "rocketmq_consumer_group_1001"
        group2: "rocketmq_consumer_group_1002"
        group3: "rocketmq_consumer_group_1003"
        group4: "rocketmq_consumer_group_1004"
        group5: "rocketmq_consumer_group_1005"
        group6: "rocketmq_consumer_group_1006"
        group7_1: "rocketmq_consumer_group_1007_1"
        group7_2: "rocketmq_consumer_group_1007_2"
        group7_3: "rocketmq_consumer_group_1007_3"
        group7_4: "rocketmq_consumer_group_1007_4"
        group7_5: "rocketmq_consumer_group_1007_5"
        group8: "rocketmq_consumer_group_1008"
        transaction_group9: "rocketmq_consumer_transaction_group_1009"
        group10: "rocketmq_consumer_group_10010"
        group11: "rocketmq_consumer_group_10011"
        # 是否开启自动配置
        #isOnOff: on
        # 发送同一类消息设置为同一个group，保证唯一默认不需要设置，rocketmq会使用ip@pid（pid代表jvm名字）作为唯一标识
        #groupName: "rocketmq_group_1001"
        # 消费者订阅的主题topic和tags（*标识订阅该主题下所有的tags），格式: topic~tag1||tag2||tags3;
        #topics: TestTopic~TestTag;TestTopic~HelloTag;HelloTopic~HelloTag;MyTopic~*
        # 消费者线程数据量
        #consumeThreadMin: 5
        #consumeThreadMax: 32
        # 设置一次消费信心的条数，默认1
        #consumeMessageBatchMaxSize: 1


